# Generated by Django 3.2.7 on 2021-09-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=15)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=15)),
                ('zoning_type', models.CharField(choices=[('C', 'Commercial'), ('I', 'Industrial'), ('M', 'Mixed Use')], default='C', max_length=1)),
                ('web_url', models.URLField(max_length=100)),
                ('full_img', models.ImageField(upload_to='img/full/')),
                ('thumbnail_img', models.ImageField(upload_to='img/thumbnail/')),
                ('sold', models.BooleanField()),
                ('sold_year', models.IntegerField(blank=True, null=True)),
                ('acquired', models.IntegerField(blank=True, null=True)),
                ('acquired_company', models.CharField(blank=True, max_length=50)),
                ('acquired_text', models.TextField(blank=True, default='')),
                ('property_text', models.TextField(blank=True, default='')),
                ('history_text', models.TextField(blank=True, default='')),
                ('redevelopment_text', models.TextField(blank=True, default='')),
                ('current_status_text', models.TextField(blank=True, default='')),
                ('project_manager_name', models.CharField(blank=True, max_length=100)),
                ('project_manager_email', models.EmailField(blank=True, max_length=254)),
                ('property_manager_name', models.CharField(blank=True, max_length=100)),
                ('property_manager_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
