# Generated by Django 3.2.7 on 2021-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=9, editable=False, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=9, editable=False, max_digits=15)),
                ('zoning_type', models.CharField(choices=[('C', 'Commercial'), ('I', 'Industrial'), ('M', 'Mixed Use')], default='C', max_length=1)),
                ('web_url', models.URLField(max_length=100)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('sold', models.BooleanField()),
                ('sold_year', models.IntegerField(blank=True)),
                ('acquired', models.IntegerField(blank=True)),
                ('acquired_company', models.CharField(blank=True, max_length=50)),
                ('property_text', models.TextField()),
                ('history_text', models.TextField()),
                ('redevelopment_text', models.TextField()),
                ('current_status_text', models.TextField()),
                ('property_manager_name', models.CharField(max_length=50)),
                ('property_manager_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
