# Generated by Django 3.2.7 on 2021-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='region',
            field=models.CharField(choices=[('W', 'Western U.S.'), ('M', 'Midwest U.S.'), ('S', 'Southeast U.S.')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='development',
            name='zoning_type',
            field=models.CharField(choices=[('U', 'Unassigned'), ('C', 'Commercial'), ('I', 'Industrial'), ('M', 'Mixed Use')], default='U', max_length=1),
        ),
    ]
