# Generated by Django 3.2.7 on 2021-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0002_auto_20210923_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='acquired',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='sold_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
