# Generated by Django 3.2.7 on 2021-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0002_auto_20211006_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
