# Generated by Django 3.2.7 on 2021-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_auto_20210924_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='project_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='development',
            name='project_manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='development',
            name='property_manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
