# Generated by Django 3.2.7 on 2021-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_auto_20211006_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='web_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
