# Generated by Django 3.2.7 on 2021-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0004_auto_20210924_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='acquired_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='development',
            name='current_status_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='development',
            name='history_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='development',
            name='property_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='development',
            name='redevelopment_text',
            field=models.TextField(default=''),
        ),
    ]
