# Generated by Django 3.2.7 on 2021-09-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='img/team/')),
                ('university1', models.CharField(blank=True, max_length=400)),
                ('major1', models.CharField(blank=True, max_length=400)),
                ('university2', models.CharField(blank=True, max_length=400)),
                ('major2', models.CharField(blank=True, max_length=400)),
                ('employee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.employeetype')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.office')),
            ],
        ),
    ]
