# Generated by Django 3.2.7 on 2021-09-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
